### PR TITLE
Improve compatibility with APPUiO

### PR DESCRIPTION
**Pull request by Kidswiss**
Now with k8s 1.29.x and networkpolicy support.

Also installs espejo with a rule to create an approximation of APPUiO's default network policies in each appcat namespace.

### CODE REVIEW

**Review by zugao — APPROVED** [review]
LGTM but I would set the espejo deployment and all its rbac into a different folder, for better grouping

**Comment by Kidswiss** [comment]
> LGTM but I would set the espejo deployment and all its rbac into a different folder, for better grouping

Should I also create a separate make target then? one for espejo und one for the whole netpol stuff?

**Comment by zugao** [comment]
> > LGTM but I would set the espejo deployment and all its rbac into a different folder, for better grouping
> 
> Should I also create a separate make target then? one for espejo und one for the whole netpol stuff?

would be better in my opinion and more clear. I would not be surprised if we would soon have custom permissions simulated here with Espejo.

**Comment by Kidswiss** [comment]
> > > LGTM but I would set the espejo deployment and all its rbac into a different folder, for better grouping
> > 
> > 
> > Should I also create a separate make target then? one for espejo und one for the whole netpol stuff?
> 
> would be better in my opinion and more clear. I would not be surprised if we would soon have custom rbac permissions simulated here with Espejo.

Done

@tobru I also fixed the typo in the commit :D

**Review by zugao — COMMENTED** [review]
LGTM again

**Pull request merged**
